### ISSUE TITLE
quill::detail::init_signal_handler() breaks segfault backtrace signal handlers

### ISSUE THREAD

**Issue by xanderdunn** [odygrd/quill#110]
I'm calling `quill::detail::init_signal_handler()` in my project so that quill gracefully handles its messages when the program unexpectedly terminates. However, I've noticed that it breaks the segfault debugging handlers described [here](https://stackoverflow.com/questions/77005/how-to-automatically-generate-a-stacktrace-when-my-program-crashes). Both manually defining a `signal(SIGSEGV, handler)`, as well as using libSegFault.so are superseded by the quill handler and are silent when using quill's `init_signal_handler` is used.

Could other handlers be used in addition to the quill handler, or could the quill handler log a backtrace so that the above handlers aren't necessary?

If this is known and expected behavior then this can be closed. For now I will have to switch between these different handlers as I'm debugging my software.

**Comment by odygrd** [comment]
Hey, 

The signal handler functionality in quill is for people who want to avoid setting up their own handlers. Therefore no other handlers can be used in addition to the quill handler.

I didn't spend much time on getting and printing backtraces due to difficulties supporting that for multiple platforms, so it is not possible to print one.

There isn't anything special required in the signal handler other than calling `quill::flush()` and waiting for the log to flush before killing the process. The only things to be careful about is 1) you want to enter and flush once and not multiple times when many threads crash at the same time and 2) if the backend worker thread crashes you don't want it to flush itself.

Since you have your own custom handlers, I would recommend the following :

a. write your own handlers with the custom functionality you need. Then you can add into them the logic for the quill signal handler from [here](https://github.com/odygrd/quill/blob/master/quill/src/detail/SignalHandler.cpp#L123). As you can see from that function you basically just need to call `quill::flush();` 

b. In quill when you call `start` to start the backend worker thread, keep the variable `with_signal_handler = false` and setup any signal/exception handling in your own thread (in this step quill calls `init_exception_handler` on the backend worker step when `with_signal_handler = true` but since you are setting up your own handlers you would rather do that yourself)

https://github.com/odygrd/quill/blob/6cd23621307937d266034f51207b477b93f93001/quill/include/quill/Quill.h#L56 

https://github.com/odygrd/quill/blob/ad0ef03ea2873d2684e3b9eeccc40a6278b88ed3/quill/include/quill/detail/LogManager.h#L135

c. Since you are developing on windows, then you need to setup a signal handler on new thread you spawn calling the handlers from `a`

Let me know if you have any further issues

**Comment by xanderdunn** [comment]
Thanks, calling `quill::flush()` from my handler will be sufficient. 

I'm developing on Ubuntu, but I think your earlier points are all the same.
