### ISSUE TITLE
Printf style support

### ISSUE THREAD

**Issue by WayneY** [odygrd/quill#121]
I am working on changing our log lib to quill by replacing the old marcos definitions. The replacing would be easy since those marcos are all defined in a single header file. But the old log is using printf style, and replacing all the ocurrence of the log to the new style would be a much heavier work than just changing a single file. 

I find quill is using project fmt as its formatter, and fmt has already supported the old printf format style.  Could you help to enlighten me that where could I modify to make quill support printf style too? I tried to read the codes but got lost ...

**Comment by odygrd** [comment]
Hello, this is currently not supported. 

I guess it would be possible but not sure how easy it would be to support this additional format. 
Maybe the easier solution would be to implement a different formatter that handles this instead of using the PatternFormatter.

However, at the moment Quill as part of it's design is using `fmt::format_to` to write to a buffer, but it looks like there is not an equivalent `fmt::printf_to` for the fmt printf API

If you pass 

`LOG_INFO(logger, "Elapsed time: %.2f seconds", 1.23);`

then you would get the equivalent of :

`fmt::format("Elapsed time: %.2f seconds", 1.23)` 

Your desired behaviour I think comes from :

`fmt::printf("Elapsed time: %.2f seconds", 1.23);`

but quill underneath is using `fmt::format_to` to format :
1) https://github.com/odygrd/quill/blob/fa9b53f49732765ed242b7372ec4197e89f381ee/quill/include/quill/PatternFormatter.h#L420

2) 
https://github.com/odygrd/quill/blob/fa9b53f49732765ed242b7372ec4197e89f381ee/quill/include/quill/PatternFormatter.h#L448

**Comment by WayneY** [comment]
Very thanks for your help!

Now I am starting to modify the PateernFormatter.h.  The line locations are a little different since I am on a Linux platform, but that does not matter much.  

The modification I made:

1. In the `printf.h` of fmt bundle, add a function named `fmt::my_printf`,  the declaration is like this:

```

  template <typename S, typename... Args, FMT_ENABLE_IF(detail::is_string<S>::value)>
  inline int my_printf(ftm::memory_buffer& buffer, const S& format_str, const Args&... args) ;

```


2. In the   Args  version of `PatternFormatter::format` (there are two versions of `PatternFormatter::format` ), change the  `fmt::format_to` to a `fmt::my_printf`, leaving the other version unchanged.


I used the example_backtrace for testing, and interestingly found that only the  LOG_BACKTRACE will go the printf route, and the LOG_INFO/LOG_ERROR... still go the unchanged one.

I tried to modify the other version too, but failed to convert the type of parameter "fmt_arg_store". 

Now my question is: what makes the two types of macros behaving differently? I see the `log`  function in `Logger.h` has a `std::enable_if_t` to check if the log is  IsBackTraceLogRecord.  But where is the exact place do they apart?

**Comment by odygrd** [comment]
Quill is using two different queues to push data, one queue is used when you log only built-in types and the second is used for user defined types. The second queue is slightly slower because we need to add padding to the user defined types to cache align them and call their destructor on the backend thread.

`PatternFormatter::format` version with `fmt::dynamic_format_arg_store<fmt::format_context>`  as arg is using the built-in type queue because of the example logging built-in types. 

You can disable the built-in type queue and use a single queue for everything. In that case the `PatternFormatter::format`  that is using `fmt::format_to` will always be called. 

You can do that if you compile quill with `QUILL_DISABLE_DUAL_QUEUE_MODE=ON`. 

Please re-open if you need further help
