### ISSUE TITLE
RuntimeError: enable_console_colours needs to be called before quill::start()

### ISSUE THREAD

**Issue by lorenck** [odygrd/quill#167]
Quill library has been linked into a shared object. 
It is possible that quill::start is called multiple times, but why should it fail with a runtime error?
I suspect that when that happens then I see this error.
The colors are set every time before quill::start() is called.

**Comment by odygrd** [comment]
hello, this is expected behaviour and kind of limitation. 

When you call `enable_console_colours` the caller thread that is calling that function is setting up some unsafe stuff what will be later on used by the backend worker thread that is writing to console/file.

To avoid using any synchronisation the library expects that to happen **before** the backend worker has spawn.

When you call `quill:start()` for the first time then the backend worker thread spawns and you can not call `enable_console_colours` anymore as it is unsafe.

That is happening here https://github.com/odygrd/quill/blob/master/quill/src/Quill.cpp#L169

Please try to call `quill::start()` only once in your application

**Comment by odygrd** [comment]
I have added some extra protection to `quill:start()` in the case when `true` is passed to use a signal handler. `quill:start(true)` will now run only once even if it is called multiple times.

This is in commit ba38f5a5f7f005922cd11a984965624a7afc6bf8

However you do not need the above commit in your code you can use :

```c++
  try
  {
    quill::enable_console_colours();
    quill::start();
  }
  catch (quill::QuillError const&)
  {
  }
```

**Comment by lorenck** [comment]
Thanks, this is helpful.

**Comment by odygrd** [comment]
closing for now, please re-open if you have any more issues
