### ISSUE TITLE
Support or forbid usage of fmt::streamed

### ISSUE THREAD

**Issue by eugene536** [odygrd/quill#189]
fmtlib9[ disabled automatic](https://github.com/fmtlib/fmt/releases) std::ostream insertion operator. Since then we need to define formatters or pass values using `fmt::streamed`.

The async logger should either deep copy such arguments or forbid using `fmt::streamed` to avoid bugs.

example
```
#include "quill/Quill.h"

int main()
{
  quill::start();
  auto logger = quill::get_logger();

  std::string s(100, 'S');
  LOG_ERROR(logger, "streamed {}", fmt::streamed(s));
  s = std::string(100, 'D');

  quill::flush();
}
```

It should print `SSSS` but it shows `DDDD`.

**Comment by odygrd** [comment]
Hello, thanks for reporting this. 

Unfortunately, it is not straight forward supporting `fmt::streamed()`. It requires several changes during serialization/deserialization that they can get more complicated for types such as `fmt::detail::streamed_view<std::string>` because we also need to count the size and characters of the underlying string while encoding.

I might give it another go in the future to support it, but for now it is disabled. The workaround is to provide the fmt::formatter specialization inherited from ostream_formatter.
```template <> struct fmt::formatter<T> : ostream_formatter {};```
