### ISSUE TITLE
Core dump while non-default QUILL_QUEUE_CAPACITY

### ISSUE THREAD

**Issue by skrydg** [odygrd/quill#194]
The diff bellow generate a core dump. 
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 17616e7..139143e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -11,7 +11,7 @@ option(QUILL_NO_EXCEPTIONS "Build without exceptions with -fno-exceptions flag"

 option(QUILL_USE_BOUNDED_QUEUE "Build with bounded queue instead of unbounded" OFF)

-option(QUILL_BUILD_EXAMPLES "Build the examples" OFF)
+option(QUILL_BUILD_EXAMPLES "Build the examples" ON)

 option(QUILL_BUILD_TESTS "Build the tests (Requires https://github.com/google/googletest to be installed)" OFF)

diff --git a/examples/CMakeLists.txt b/examples/CMakeLists.txt
index ab7e1cc..a095394 100644
--- a/examples/CMakeLists.txt
+++ b/examples/CMakeLists.txt
@@ -1,3 +1,4 @@
+add_definitions(-DQUILL_QUEUE_CAPACITY=262144)
 add_executable(example_backtrace example_backtrace.cpp)
 target_link_libraries(example_backtrace quill)

@@ -59,4 +60,4 @@ add_executable(example_trivial_system_clock example_trivial_system_clock.cpp)
 target_link_libraries(example_trivial_system_clock quill)

 add_executable(example_user_defined_types example_user_defined_types.cpp)
-target_link_libraries(example_user_defined_types quill)
\ No newline at end of file
+target_link_libraries(example_user_defined_types quill)
diff --git a/examples/example_trivial.cpp b/examples/example_trivial.cpp
index 7d37284..999ccff 100644
--- a/examples/example_trivial.cpp
+++ b/examples/example_trivial.cpp
@@ -3,7 +3,7 @@
 /**
  * Trivial logging example
  */
-
+#include "unistd.h"
 int main()
 {
   // Start the logging backend thread
@@ -20,6 +20,7 @@ int main()
     // Change the LogLevel to print everything
     logger->set_log_level(quill::LogLevel::TraceL3);

+    for (int i = 0; i < 100000; i++) {
     LOG_TRACE_L3(logger, "This is a log trace l3 example {}", 1);
     LOG_TRACE_L2(logger, "This is a log trace l2 example {} {}", 2, 2.3);
     LOG_TRACE_L1(logger, "This is a log trace l1 {} example", "string");
@@ -31,6 +32,8 @@ int main()

     std::array<uint32_t, 4> arr = {1, 2, 3, 4};
     LOG_INFO(logger, "This is a log info example {}", arr);
+    usleep(100);
+    }
   }

   // b) Or like this
@@ -90,4 +93,4 @@ int main()
   }

   LOG_INFO(default_logger, "Existing logger names {}", logger_names);
-}
\ No newline at end of file
+}
```

**Comment by odygrd** [comment]
hello, 

Adding `add_definitions(-DQUILL_QUEUE_CAPACITY=262144)` in `examples/CMakeLists.txt` makes the examples to build with that flag, but _**not**_ the actual `quill` library. 

Since quill is not a header only library some of the options require the whole library to be re-compiled with that new value, otherwise it won't work. This is mentioned here https://github.com/odygrd/quill/blob/master/quill/include/quill/TweakMe.h#L85

If quill is already pre-compiled and installed on your system you won't be able to change the queue capacity ... the value can only be set once when quill got compiled

If you are compiling quill together with the rest of your project e.g. as a subrepo you can call `add_definitions(-DQUILL_QUEUE_CAPACITY=262144)` **_before_** `add_subdirectory(quill)` or I think you can pass this option in the command line when you run cmake with `-DCMAKE_CXX_FLAGS:=-DQUILL_QUEUE_CAPACITY=262144`

Another easy way to change it if quill is compiled with the rest of the project is to just edit the Tweakme.h file

**Comment by odygrd** [comment]
This core dump happens when quill library is compiled with a different size that the one passed externally. 

I tried yesterday by adding `add_definitions(-DQUILL_QUEUE_CAPACITY=262144)` here https://github.com/odygrd/quill/blob/master/CMakeLists.txt#L161 and it worked. 

I can try again in a few hours, in the meanwhile could you please try adding `add_definitions(-DQUILL_QUEUE_CAPACITY=262144)` in your root CMakeLists ?

**Comment by amertsalov** [comment]
It's working fine by adding add_definitions in root CMakeLists.

My suggestion is adding some compile time mechanism with good error message to prevent this situation in future.
