### ISSUE TITLE
LOG_BACKTRACE log message timestamp does not appear in order in the log file

### ISSUE THREAD

**Issue by chinahuangyong** [odygrd/quill#209]
when i use the example './example_backtrace', but log timestamp is disorganization.
![image](https://user-images.githubusercontent.com/20627061/205198064-cfe1f716-bf18-4176-9ab5-ad9a89d22ed4.png)

**Comment by odygrd** [comment]
Hey, thanks for reporting and for using quill.

`LOG_BACKTRACE` is a bit special because of the way it works and it can log messages out of order.

Backtrace stores previous log messages and only log them e.g. in case of an error. The backtrace messages contain their original timestamp at the time they got logged.

Looking at the example (https://github.com/odygrd/quill/blob/master/examples/example_backtrace.cpp#L28) they were logged earlier.

Imagine for example

```c++

    // flush backtrace on LOG_ERROR
    logger->init_backtrace(2, quill::LogLevel::Error);

    // logged at t1 but not written to the file
    LOG_BACKTRACE(logger, "Backtrace log {}", 3);

    // logged at t2 but not written to the file
    LOG_BACKTRACE(logger, "Backtrace log {}", 4);

    // logged at t3 and written to the file
    LOG_INFO(logger, "AFTER backtrace Example {}", 1);

    // logged at t4 and written to the file. 
    // Here we also write the stored messages from the backtrace with t1 and t2
    LOG_ERROR(logger, "An error has happened, Backtrace is also flushed.");
```

Let me know if you have any other questions / issues
