### ISSUE TITLE
Throughput benchmarks

### ISSUE THREAD

**Issue by madhur4127** [odygrd/quill#236]
I think its important to have throughput benchmarks along with latency benchmarks. This helps in making an informed decision to choose a logger.

Since there's a single background logging thread, there's a chance of multiple threads choking it up therefore making throughput benchmarks even more critical.

**Comment by odygrd** [comment]
Hey, there is a throughput benchmark in the repo. I have also put a section in the readme now https://github.com/odygrd/quill#throughput

Even when multiple threads are logging, in the worst case they might allocate more space for the queue but the hot threads won't block. The logging thread will always prioritise to completely empty the queues of each hot thread on each iteration. 

The logging thread will eventually catch up at some point. Otherwise if you are always logging at the max throughput rate you are going to anyway either run out of disk space or end up with very large log files that makes it impossible to search anything there.

**Comment by madhur4127** [comment]
Thanks those benchmarks are good enough for my use case.

**Comment by odygrd** [comment]
you're welcome, if any issues please report. 
Note that I have benchmarked latest `master`. 
Currently I am testing this version in UAT so far without any issues. Planning to release it as `v2.7.0` in ~ 2 weeks or so
