### ISSUE TITLE
std::bad_alloc exception on Mingw-w64

### ISSUE THREAD

**Issue by jwillikers** [odygrd/quill#25]
My application crashes when compiled with Mingw-w64 (GCC 9.3) on Windows 10 when run using the recent commit 6248396b433bda060320eca0e9d181bb82f74d22.
An unexpected `std::bad_alloc` exception is thrown.
I am able to re-create the issue by running the `example_custom_formatter` example target.
I tried to run the tests on Mingw-w64 but there were compilation issues with the use of `std::ifstream` and `std::wstring` in the `quill::testing::file_contents` function.

**Comment by odygrd** [comment]
Hey thanks for reporting !

The timestamp format in the example is not supported by `strftime` on mingw-w64. But quill doesn't expect that and thinks that `strftime` failed because the provided buffer was not big one and tries to allocate more and allocates forever.

If you change the timestamp format to something like `"%d-%m %H:%M:%S.%Qms"` it will worked. 

Most of the yellow ones. in this page are not supported by Mingw-w64, at least that the behaviour i see with mingw 8.1.0
http://www.cplusplus.com/reference/ctime/strftime/

**Comment by odygrd** [comment]
For MinGw linking against `libucrtbase` looks like it resolves the issue with `strftime` formatting. In the worst case it won't crash but instead print an invalid timestamp. 
When not linking against `libucrtbase` it looks like only the white format specifiers from the above link are supported..
Please let me know if you have further issues

**Comment by jwillikers** [comment]
Linking to `libucrtbase` works great! Thank you.
