### ISSUE TITLE
Example of pinning the the backend logging thread

### ISSUE THREAD

**Issue by qiuwei** [odygrd/quill#272]
Is there any documentation or example of pinning the backend logging thread to a CPU core?

If I have multiple application using quill running on the same machine, is it OK to pin all of the backend logging thread to the same CPU core?

**Comment by brendene** [comment]
Here is an example: https://github.com/odygrd/quill/blob/master/benchmarks/backend_throughput/quill_backend_throughput.cpp#L13

The backend logging thread is usually spinning so you probably want to have it sleep a little if there are multiple running on the same core https://github.com/odygrd/quill/blob/f28dfd79054da2f6f77d5c0740f31fef0d17dd51/quill/include/quill/Config.h#L40

**Comment by qiuwei** [comment]
Thanks for the info! Very helpful!

**Comment by brendene** [comment]
You could also try setting backend_thread_yield to true https://github.com/odygrd/quill/blob/master/quill/include/quill/Config.h#L33 

This will result high CPU usage, so it depends on how performant you want the backend thread to be vs how many of them you have on a single core

**Comment by odygrd** [comment]
hey, there is an example here https://github.com/odygrd/quill/blob/master/examples/example_configure_backend.cpp#L20

As brendene said above it depends on your use case.

If you have many hot threads and your hot threads are logging really a lot (like every 1-2 microseconds lets say) you can use an exclusive cpu for the backend logging thread. That means that you are reducing the possibility of the backend logging thread falling behind processing too many messages. If that happens it can cause a memory allocating due to allocating extra space for the message queue.

If the hot threads are logging in normal rates then I don't see any reason to pin it to an exclusive cpu. Usually you have a shared core for things that are not too latency sensitive and you can pin it there. It is fine to pin multiple logging threads on the same core.

**Comment by qiuwei** [comment]
> hey, there is an example here https://github.com/odygrd/quill/blob/master/examples/example_configure_backend.cpp#L20
> 
> As brendene said above it depends on your use case.
> 
> If you have many hot threads and your hot threads are logging really a lot (like every 1-2 microseconds lets say) you can use an exclusive cpu for the backend logging thread. That means that you are reducing the possibility of the backend logging thread falling behind processing too many messages. If that happens it can cause a memory allocating due to allocating extra space for the message queue on the hot path.
> 
> If the hot threads are logging in normal rates then I don't see any reason to pin it to an exclusive cpu. Usually you have a shared core for things that are not too latency sensitive and you can pin it there. It is fine to pin multiple logging threads on the same core.

Thanks for the detailed instructions. We run multiple hot threads. The hot threads are logging in at normal rates. We would like to pin the logging thread because we do not want the logging thread scheduled accidentally on the same core as any of the hot threads. The hot threads are latency sensitive.
