### ISSUE TITLE
QUILL_USE_BOUNDED_QUEUE cause assertion error : "Object should always be cache aligned"

### ISSUE THREAD

**Issue by toge** [odygrd/quill#30]
Thank you for fast development. I love using this library.
When I try to use QUILL_USE_BOUNDED_QUEUE in In quill 1.3.1, 
I met the assertion error message: 
```
.../include/quill/detail/BoundedSPSCQueue.h:362: quill::detail::BoundedSPSCQueue<TBaseObject, Capacity>::Handle quill::detail::BoundedSPSCQueue<TBaseObject, Capacity>::try_pop() [with TBaseObject = quill::detail::RecordBase; long unsigned int Capacity = 262144]: Assertion `(reinterpret_cast<uintptr_t>(buffer_pos) % CACHELINE_SIZE == 0) && "Object should always be cache aligned"' failed.
```
Please tell me workaround.

my environment : Fedora 32, gcc 10.1, glibc 2.31
quill version: 1.3.1

**Comment by odygrd** [comment]
Hey,

To use `QUILL_USE_BOUNDED_QUEUE` mode since the library is not header only this is one of the three options that require the library to be recompiled with this option.
In `TweakMe.h` there is a comment 
`/* Anything after this point requires the whole library to be recompiled with the desired option. */`

Can you please let me know how you are enabling `QUILL_USE_BOUNDED_QUEUE` ? 

1 ) Can you make sure that `QUILL_USE_BOUNDED_QUEUE` is uncommented in `TweakMe.h` instead of defining it before including `Quill.h` and then recompile the `quill` with the option ?

It sounds like the issue is the above. 

If you used a package manager to install quill it won't be possible to use the bounded queue as the library is already compiled with the unbounded queue.


If that is not the case can you give me some more information for e.g. a) does it happens every time, and b) if you can figure out the type of the object you are trying to log when the assertion fires ?

Thanks for reporting !

**Comment by toge** [comment]
Thank you for precise comment!

As you mentioned, I use quill by conan package manager.
Now I understand the reason of assertion failure.

One more question.
Is there any plan to add recipe's option about `QUILL_USE_BOUNDED_QUEUE`?
For example, if `use_bounded_queue` option is set, conan recipe modifies TweakMe.h to uncomment `QUILL_USE_BOUNDED_QUEUE` before compile.

**Comment by odygrd** [comment]
I am planning to add it to conan as an option with version `1.3.2` hopefully over the next few days.
There will be 2 conan options `with_bounded_queue` and `with_exceptions`.

It wasn't there because as you can see in the benchmarks the difference is really minor on most cases and i consider it more advanced feature.

For now, until the conan package is available, maybe you can define a bigger queue, like
```c++ 
#define QUILL_QUEUE_CAPACITY 524288
#include "quill/Quill.h"
```

**Comment by toge** [comment]
Thank you very much!
I will try your solution and wait for next version.

**Comment by odygrd** [comment]
Even after using the bounded queue version, it is useful to have this option to easily change the size of the bounded queue if you are dropping too many messages

**Comment by odygrd** [comment]
When this PR get's merged you can you the bounded queue option on conan with 1.3.2

https://github.com/conan-io/conan-center-index/pull/1644

**Comment by toge** [comment]
Thanks!

**Comment by odygrd** [comment]
Hey @toge option should now be available on conan. Please also use version 1.3.2
