### ISSUE TITLE
use a custom namespace for the bundled libfmt

### ISSUE THREAD

**Issue by azuresigma** [odygrd/quill#310]
Gcc 13 has format library implemented now. Can quill use format library from c++20 when gcc13+ is used?
This will solve the versioning issue for different fmt libraries when using quill in a large application. 

* in-house library X uses quill, which uses fmt version 10. 
* another in-house application uses fmt version 7(because fmt is so popular), and then want to use library X. Now this application will be forced to upgrade fmt version to 10. This might be a big change for the application.

**Comment by odygrd** [comment]
Quill supports using an external fmt library if you pass the compiler flag 'QUILL_FMT_EXTERNAL' https://github.com/odygrd/quill/blob/master/quill/include/quill/TweakMe.h#L182
This is the default option when you install it via package managers for example vcpkg

In the above case the first library that is using quill will have to use the libfmt which is installed on the system and pass the external flag to quill

Another thing that is might be possible to do is to change the namespace of the bundled fmt to our own namespace so that using quill with bundled fmt should be completely independent from any system installed libfmt library 

I would ideally like to use 'std::format' and have zero 3rd party dependencies that it is not so simple. Quill is using a lot of internal parts of libfmt. we could create our own classes to replace them. However, there is some features of libfmt that have not been standarised and quill requires them. The main one is dynamically passing the types that you want to the format function. The backend thread is popping objects from the queue and passing them dynamically to the format function. (https://github.com/odygrd/quill/blob/master/quill/include/quill/detail/Serialize.h#L123). That feature does not exist in 'std::format'. 

I tried in the past to create my own wrapper that will implement those additional logic and use std::format but those parts are not standarised 

https://stackoverflow.com/questions/69857618/fmtdynamic-format-arg-store-replacement-implementation-for-stdformat

**Comment by azuresigma** [comment]
Thank you for the details and sorry for the delay in replying to this thread. 
Given std might never close the gap with quill functions and implementing your own fmt functions might take some time to develop/test/stabilize, I think it is best to have the bundled quill in your own namespace. 
We are using externl fmt library now. 1 issue we have now is, we have to build same quill with different fmt versions to have quill-2.1.0-fmt-9, quill-2.1.0-fmt-10 for example.

**Comment by odygrd** [comment]
I still need to do some more testing on this but I have done some initial work

**Comment by odygrd** [comment]
the custom namespace seems good.. I tested with external fmt and also with bundled fmt and a system installed fmt on different version..
Let me know of any  issues once you have a chance to use it. I will do the next release with it sometime within the next 2 weeks
