### ISSUE TITLE
create_logger requires std::move on an std::shared_ptr

### ISSUE THREAD

**Issue by ivannp** [odygrd/quill#326]
[This change](https://github.com/odygrd/quill/commit/9d2a7b6f6a3b526c15281b9b7a0d9d595cb320da) forces callers of `quill::create_logger` to do `std::move` now. It should be taken as by-value.

**Comment by odygrd** [comment]
Hey, it is there as a protection so that the user won’t keep a copy of this shared_ptr in his application. If that happens the handler won’t be removed when all the Logger objects that are using it are removed.

if you need to reuse the same Handler in multiple Loggers then you should call ‘quill::create_handler’ again. When the Handler already exists it won’t create a new instance but instead return you a ‘shared_ptr’ to the existing Handler object that you can again move to the new logger you are creating.

**Comment by iotozake** [comment]
While fixing my code, I looked up a bit and It seems that this use of a `shared_ptr` is a bit of [an anti-pattern](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines). Some static analysis tools might even flag it.

**Comment by odygrd** [comment]
I have implemented a new function quill::get_handler(filename) which allows users to retrieve an existing handler. For now, I am closing this task, but please feel free to leave any comments or feedback.
