### ISSUE TITLE
please add comparation with 'lwlog'

### ISSUE THREAD

**Issue by walkthetalk** [odygrd/quill#342]
https://github.com/ChristianPanov/lwlog
which is also declare low latency as the main feature. can we do a benchmark with it?

**Comment by odygrd** [comment]
lwlog is a synchronous logging library. 
With quill formatting to string and File I/O are handled by a background thread and not on the hot path like with a synchronous logging library. 
PRs are welcome, although I don't believe it is a fair comparison (asynchronous hot path will always be faster because it doesn't have to do any string formatting or write to the file)

**Comment by odygrd** [comment]
Closing for now
