### ISSUE TITLE
Why Should BoundedQueueImpl Allocate 2 times of capacity?

### ISSUE THREAD

**Issue by takohack** [odygrd/quill#347]
<img width="905" alt="image" src="https://github.com/odygrd/quill/assets/41536101/5f340709-1fac-4685-8e32-eb7a5362f215">

**Comment by takohack** [comment]
![image](https://github.com/odygrd/quill/assets/41536101/b8fe1f0b-10de-44c5-bf93-a3d36d103d82)
![image](https://github.com/odygrd/quill/assets/41536101/903d12e1-e66d-4233-b82f-2040a1cd7af0)
Since prepare_read() and prepare_write Only Return address at [_storage,storage + _mask] address space

**Comment by odygrd** [comment]
hey, this is because we are reading and writing bytes from the queue as we write different types each time.
imagine you have 1 free byte at the end of the buffer and several free bytes at the start of the buffer and you want to push an int (4 bytes)
you would need to leave empty space at the end of the buffer as unused and then wrap around. then each time you need
to manage this space in your logic.
To avoid doing this you can instead allocate double the amount of memory and you can safely overflow
or you can use the magic ring buffer technique which is essentially the same thing without the extra memory overhead (https://lo.calho.st/posts/black-magic-buffer/)
