### ISSUE TITLE
Inline logging output of fmtquill::join() outputs wrong data

### ISSUE THREAD

**Issue by YuukiHogo** [odygrd/quill#356]
In multithreaded environment the code below outputs random hex string:
```
std::vector<uint8_t> data(100);
LOG_DEBUG(quill::get_logger(), "data: {:02x}", fmtquill::join(data, ""));
```

Workaround:
```
std::vector<uint8_t> data(100);
auto aux = fmtquill::format("{:x02}",  fmtquill::join(data, ""));
LOG_DEBUG(quill::get_logger(), "data: {}", aux);
```

Is there a better way to fix this?

**Comment by odygrd** [comment]
The problem seems to be that fmt join returns a `view`

if you try this it will fail with error 'passing views as lvalues is disallowed'

```c++
  std::vector<uint8_t> data(100);
  auto s = fmtquill::join(data, "");
  fmtquill::format("data: {:02x}", s);
```

The logger makes a copy of the view and then the backend thread tries to format it. 

I am not sure if that can be supported. It would be good tho to fail with a static assertion when a view is passed to a LOG macro

Your workaround is good with the only drawback that the format is done on the hot thread but i dont think we have another option here

**Comment by odygrd** [comment]
This is now disabled in compile time with 4cc4dae

As you mentioned please use the provided workaround for now

```c++
std::vector<uint8_t> data(100);
auto aux = fmtquill::format("{:x02}",  fmtquill::join(data, ""));
LOG_DEBUG(quill::get_logger(), "data: {}", aux);
```
