### ISSUE TITLE
Conan packages for quill 4

### ISSUE THREAD

**Issue by TillAlex** [odygrd/quill#449]
Any plans when you will release conan packages for quill 4?

**Comment by odygrd** [comment]
Hello, there were some other contributors actively updating them in the past. My plan is to wait and see if they update it within the next 3-4 weeks and if not, I am planning to do it myself

**Comment by odygrd** [comment]
Thank you to all the package contributors, @RT2Code, @toge, and @chenrui333. I see that there are PRs for version 4 across Conan, Vcpkg, and Homebrew :pray:

**Comment by RT2Code** [comment]
Thank you for your hard work on quill. It's my go-to logger library, and I love my project's dependencies to be up to date, that's why I update the vcpkg port for [almost every new release](https://github.com/microsoft/vcpkg/commits/a849250c3b5e5a6ce476064f2ede28ad8f0da3d4/ports/quill/vcpkg.json?before=a849250c3b5e5a6ce476064f2ede28ad8f0da3d4+35). :wink:
