### ISSUE TITLE
Linkage problem when linking to shared library defining a custom formatter

### ISSUE THREAD

**Issue by TillAlex** [odygrd/quill#472]
I have a library implementing a custom formatter deriving from fmtquill::formatter. When building this library and statically linking to it everything is ok, but when linking to the static library I get a linker error complaining about an

> undefined reference to `void fmtquill::v10::detail::vformat_to<char>(fmtquill::v10::detail::buffer<char>&, fmtquill::v10::basic_string_view<char>, fmtquill::v10::detail::vformat_args<char>::type, fmtquill::v10::detail::locale_ref)'

Does anyone have an idea what I am doing wrong?

**Comment by odygrd** [comment]
It can be related to the symbol not exported for the shared library from libfmt header only version.

Would it be possible to submit an example so it's easier to investigate ?

**Comment by TillAlex** [comment]
In this case I am using Ubuntu 22.04. I will try to submit a minimal reproducer as soon as possible.

**Comment by TillAlex** [comment]
Unfortunately I was not able to generate a minimal reproducer. 

However, while playing around with my code I figured out that adding user_quill_codec.h from the quill examples makes my formatter link correctly. Digging deeper into this showed that including "quill/std/Array.h" was the main difference between the two formatters. Looking through the includes of Array.h in the end I found that I had to include "quill/bundled/fmt/format.h" in my formatter file to make it link correctly.

I do not really understand why it compiles without that include, but does not link.

**Comment by odygrd** [comment]
After v4 quill is only including core.h from fmt and not format.h by default, that way includes are minimal. 

It is also using the header only version of libfmt 

This line is also removed in the internal quill libfmt and i think that this issue might be because of this because the header only libfmt includes by default format.h but quill doesn't do it by default 

https://github.com/fmtlib/fmt/blob/e69e5f977d458f2650bb346dadf2ad30c5320281/include/fmt/core.h#L2967

On your side when using a user defined formatter please always include format.h explicitly

**Comment by TillAlex** [comment]
Ok, problem solved. Thanks for your help and for all your work here again!
