### ISSUE TITLE
How to flush logs on every new line?

### ISSUE THREAD

**Issue by asaff1** [odygrd/quill#488]
Is it possible to set the logs to always flush when a new line (similar to Python logging behavior)? print on every logging statement. Without manually calling flush each time.

Also when debugging, it takes some time the logs to appear, so it is good to have it enabled then, since cout and the logs are not ordered.

**Comment by odygrd** [comment]
it is not possible at the moment but i am adding it as a new feature for the next release. 

Since i do not want to add another if statement on the hot path and that is meant to be mainly for debugging purposes i am adding it as a preprocessor flag that has to be defined QUILL_IMMEDIATE_FLUSH (https://github.com/odygrd/quill/pull/487/commits/ff4b2082dad08850106d90fd5016823cf5eb60f6)

This means that to enable it you will have to recompile your project with the flag

**Comment by odygrd** [comment]
This is done in master branch, you can define `QUILL_IMMEDIATE_FLUSH` in the preprocessor to enable flushing on each log statement
