### ISSUE TITLE
Why convert_rdtsc_to_epoch_time(rdtsc) return 0?

### ISSUE THREAD

**Issue by williamlfang** [odygrd/quill#500]
I'm trying to get ts from function `convert_rdtsc_to_epoch_time` with argument as `rdtsc = quill::detail::rdtsc()`, which always return 0?

```c++
//setup quill:logger
g_logger_t::get_instance().init();

uint64_t const rdtsc = quill::detail::rdtsc();
uint64_t const ts = quill::detail::BackendManager::instance().convert_rdtsc_to_epoch_time(rdtsc);
logi("quill:: rdtsc:{}, ts:{}", rdtsc, ts);
```

**Comment by williamlfang** [comment]
For quill::logger, I use `quill::ClockSourceType::Tsc` sa clock source.

**Comment by odygrd** [comment]
This gets the time from the backend worker clock source

Requires the backend worker thread to be running, Backend::start()

and also at least one log statement issued, that is because the backend worker lazy inits the rtdsc clock source on the first usage 

have a look at this example 

https://quillcpp.readthedocs.io/en/latest/timestamp_types.html#getting-a-synchronized-timestamp-with-the-backend-thread-tsc-clock

to guarantee you always get it also add a logger->flush_log() right after the LOG_INFO statement. I will update the doc.

let me know if you have any issues

**Comment by williamlfang** [comment]
So much thanks to you. It finally works. I think I need to read more codes.

**Comment by odygrd** [comment]
you are welcome : ) I have updated the above example in the documentation
