### ISSUE TITLE
[feature request] user defined type support member function `std::string to_string() const` 

### ISSUE THREAD

**Issue by zhangzq** [odygrd/quill#53]
Currently, quill only support `operator<<()` for user defined type. But `<<` is rarely used (and is not compatiable with fmt and quill grammar). Could you support `std::string to_string() const`?

Here is an example:

```C++
struct User {
    std::string name;
    std::string password;

    std::string to_string() const {
        return fmt::format("{{user:{}, password:{}}}", user, password);
   }
};

int main() {
    // ....
    User user{"foo", "xxx"};
    LOG_INFO("{}", user);
}
```

**Comment by odygrd** [comment]
The main problem with this is that `quill` does not perform any formatting itself, it is all up to `fmt`.

The above statement will be passed to `fmt` like 

```c++
    User user{"foo", "xxx"};
    fmt::format("{}", user);
```

The `operator<<` support comes from `<fmt/ostream.h>` https://fmt.dev/latest/api.html#ostream-api
It is more like up to `fmt` to support `to_string` rather than quill.

**Comment by zhangzq** [comment]
OK. I'll automaticlly generate operator << for objects with `to_string()` member function myself.

Thanks.
