### ISSUE TITLE
windows headers are included - windows macros create problems

### ISSUE THREAD

**Issue by ivannp** [odygrd/quill#618]
**Describe the bug**
quill includes windows headers. This is a problem, because many windows functions are in fact macros. If there is a function in the project called `GetObject`, it's expanded by the windows `GetObjectA` or `GetObjectW`, which is horrible.

**To Reproduce**
Include `quill/Logger.h` and create a class with a `GetObject` method.

**Expected Behaviour**
Not bringing in `windows.h` is ideal.

**Environment Details**
  - Library Version: latest
  - Linkage: static
  - Operating System: windows
  - Compiler: msvc

**Comment by odygrd** [comment]
I tried to remove `windows.h` from `Logger.h` a few months ago. Since `Logger.h` and `Metadata.h` are the only headers needed for logging, it would be ideal not to include `windows.h` there. However, it wasn’t possible at the time. We rely on some OS-specific functions, and `windows.h` defines preprocessor variables that are necessary for the underlying headers, so simply including those headers didn’t work.

To minimize issues, we define `LEAN_AND_MEAN` and `NO_MINMAX` before including `windows.h`. 

I’ll give it another try in the next few days and see if there's a way around this.

**Comment by odygrd** [comment]
This update removes `windows.h` from `Logger.h` by forward-declaring the necessary functions. Now, if you build a wrapper as shown in the example below:

https://github.com/odygrd/quill/blob/master/examples/recommended_usage/recommended_usage.cpp

you should be able to log without including `windows.h`.
