### ISSUE TITLE
How to make it more convenient to support formatting for non-TriviallyCopyable types?

### ISSUE THREAD

**Issue by tqolf** [odygrd/quill#630]
I have third-party library eigen3, Eigen::Matrix is non-TriviallyCopyable, but it provides ostream interface.

for example,
``` c++
// Eigen::VectorXd is based on Eigen::Matirx

Eigen::VectorXd vec;
vec << 1, 2, 3;

static Eigen::IOFormat myfmt(4, 0, ", ", "; ", "[", "]", "", "");
std::ostringstream oss;
oss << vec.transpose().format(myfmt);
std::string str = oss.str();
```

Can I only provide specialization like this
```c++
template <>
std::string quill::format<Eigen::VectorXd>(std::string_view format_options)
{
   Eigen::IOFormat myfmt(4, 0, ", ", "; ", "[", "]", "", ""); // construct from format_options
   std::ostringstream oss;
   oss << vec.transpose().format(myfmt);
   return oss.str();
}
```

I think it's more friendly for us.

**Comment by tqolf** [comment]
Also I have read example like user_quill_codec user_defined_types_multi_format, but maybe it's not the best choice for types like that.

**Comment by tqolf** [comment]
according to the examples, I have implemented specialization as following, but failed to compile. DynamicFormatArgStore::push_back limits:
``` c++
template <>
struct fmtquill::formatter<Eigen::VectorXd> {
  constexpr auto parse(format_parse_context& ctx) { return ctx.begin(); }

  template <typename FormatContext>
  auto format(const Eigen::VectorXd& vec, FormatContext& ctx) const {
    static Eigen::IOFormat myfmt(4, Eigen::DontAlignCols, ", ", "; ", "[", "]", "", "");
    std::ostringstream oss;
    oss << vec.transpose().format(myfmt);
    return fmtquill::format_to(ctx.out(), "{}", oss.str());
  }
};

template <>
struct quill::Codec<Eigen::VectorXd> {
  static size_t compute_encoded_size(detail::SizeCacheVector& conditional_arg_size_cache, Eigen::VectorXd const& arg) noexcept {
    return sizeof(size_t) + sizeof(double) * arg.size();
  }

  static void encode(std::byte*& buffer, detail::SizeCacheVector const& conditional_arg_size_cache, uint32_t& conditional_arg_size_cache_index,
                     Eigen::VectorXd const& arg) noexcept {
    quill::Codec<size_t>::encode(buffer, conditional_arg_size_cache, conditional_arg_size_cache_index, arg.size());
    std::memcpy(buffer, arg.data(), sizeof(double) * arg.size());
    buffer += sizeof(double) * arg.size();
  }

  static Eigen::VectorXd decode_arg(std::byte*& buffer) {
    const size_t size = quill::Codec<size_t>::decode_arg(buffer);

    Eigen::VectorXd arg(size);
    std::memcpy(arg.data(), buffer, sizeof(double) * size);
    buffer += sizeof(double) * size;

    return arg;
  }

  static void decode_and_store_arg(std::byte*& buffer, DynamicFormatArgStore* args_store) { args_store->push_back(decode_arg(buffer)); }
};
```

**Comment by odygrd** [comment]
hey, the code you provided is working for me. What compiler error are you getting and what compiler are you using ?

https://godbolt.org/z/czq8KhPnv

**Comment by tqolf** [comment]
It works for me now. The DynamicFormatArgStore::push_back interface failed to compile yesterday, but now the issue is gone, and there are no logs recorded either, which is a bit strange.

I understand your concerns, but I still hope a simplified approach can be provided. Quill's efficiency is already sufficient, and the performance impact caused by user-defined specializations is actually acceptable. Implementing a codec for complex classes isn't easy, but if we could directly convert them into strings using the existing interface, it would be very intuitive and user-friendly.

**Comment by odygrd** [comment]
Thank you for your ideas and suggestions—they’re always greatly appreciated!

My main goal with the library is to make it as extensible as possible, allowing users to adapt it to their unique needs rather than trying to include every possible feature. That said, I’m always open to adding new things that could benefit others.

Regarding A -> fmt(A), you could indeed implement A -> fmt. The challenge here is that the string conversion happens twice: once to calculate the accumulated size of all arguments in a log statement and once again during encoding. Here's an example illustrating this:

https://godbolt.org/z/53eTeGo9P

Just to note, we already have something similar for trivially copyable types that works in a comparable way:

https://github.com/odygrd/quill/blob/master/include/quill/TriviallyCopyableCodec.h

The simplest and most efficient approach, which I personally prefer, is shown below. It only converts to a string once and explicitly highlights that formatting happens on the hot path. This explicitness is important, as it avoids hidden background operations:

https://godbolt.org/z/49r4zqob8

If you’re seeing no log statements, feel free to share a sample of the code that’s causing issues, along with details of your compiler and environment. I’d be happy to help troubleshoot!
