### ISSUE TITLE
Logging third party types that are not trivial and require QUILL_COPY_LOGGABLE

### ISSUE THREAD

**Issue by bl-ue** [odygrd/quill#74]
I have a 3rd party type—a custom string wrapper—and it has a method `GetText()`, which returns a `const char *`.  But since I can't modify the class definition of this type I can't add the `QUILL_COPY_LOGGABLE` macro. 

Is there any way I can create a custom formatter function for this type?

**Comment by odygrd** [comment]
The 'QUILL_COPY_LOGGABLE' macro is used to take a copy of the object so that the formatting is performed.

Are you sure it is safe to take a copy of this 3rd party type ? (e.g. it doesn't contain any mutable shared references - see https://github.com/odygrd/quill/wiki/8.-User-Defined-Types)

If yes the only way I can think of at the moment is to do something like

```c++
class my_type : public other_type
{
public:
    QUILL_COPY_LOGGABLE; /** Tagged as safe to copy **/

   // This is needed for fmt to format, make sure you include fmt/ostream.h
   // This is called by the backend worker thread on the copy of the object now because we added QUILL_COPY_LOGGABLE
    friend ostream& operator<<(ostream& os, my_type const& dt)
   {
       os << my_type.GetText();
       return os;
   }
}
```

If the type is not safe to copy consider calling `GetText()` on the caller thread which is the safest 

`LOG_INFO(logger, obj.GetText());`

**Comment by bl-ue** [comment]
@odygrd would it be possible to make it so that if an `operator<<(ostream& os, my_type const& s) { ... }` is found in the global namespace (and maybe turning on the unsafe option you mentioned above), quill would use it?

**Comment by odygrd** [comment]
it should be fine, let me know if you have any issues

**Comment by odygrd** [comment]
Closing this, please re-open if any issues
