### ISSUE TITLE
Custom handlers

### ISSUE THREAD

**Issue by TillAlex** [odygrd/quill#75]
Is there support for custom handlers? I am not sure if I just missed them in the documentation / examples. If not, are you planning to support custom handlers?

**Comment by odygrd** [comment]
It looks not possible at the moment to register a custom handler via the current API.

Also the current limitation in implementation is that the handlers are created only once. Because all the current handlers are based on a file (stdout, stderr or a filename) their existence is checked by using the name of that file. This avoids opening the same file more than once in a different handler.

This means that it would be easy to support an API call for a custom handler that is based on a file https://github.com/odygrd/quill/blob/master/quill/src/detail/HandlerCollection.cpp#L57 but if the custom handler doesn't have that requirement it needs some more redesign

What custom handler would you like to add ? Will it be writing to a file underneath ?

**Comment by TillAlex** [comment]
The custom handler I would like to add would be publishing logs via network(ZeroMQ).

What about adding a custom handler using an (unique) identifier string and a lambda that is executed for every log message? This would allow very flexible and easy implementation of custom handlers.

**Comment by odygrd** [comment]
I have created this PR that will be ready soon and should support custom handlers.
https://github.com/odygrd/quill/pull/76/files

Each handler has a unique name.
For stream handlers (that depend on a file) the unique name is also used as the underlying file name.

Please check the example -> examples/example_custom_handler.cpp

**Comment by odygrd** [comment]
@TillAlex This is now done in the above PR - please report any issues.
Are you using quill directly from master or will you require a new release ?

**Comment by TillAlex** [comment]
This solution is perfect for my case. Thanks for the quick response. This was the only thing hindering me from replacing spdlog with quill. I am using quill directly from master, so I do not require a release. And: Thank you for the great work in this project!
